M48
; DRILL file {KiCad (6.0.2)} date Sat Apr  2 12:49:49 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-02T12:49:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X55.0Y-105.0
X55.0Y-145.0
X150.0Y-105.0
X150.0Y-145.0
X249.964Y-145.0
X250.0Y-105.0
X345.0Y-105.0
X345.0Y-145.0
T0
M30
